Portfolio creation project
yegonkimutai/Create-a-Portfolio pull request #1
Opened 2023-01-12 10:56 UTC by yegonkimutai

The project concerns creation of personal portfolio using the provided templates. It also involves the use of flexbox so as to make the contents adjust to the screen size.

2023-01-12 12:54 UTC, DuaneDave requested changes
Hi @yegonkimutai  👋 , 

Good job so far on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ Meaningful commits history 💯 
✔️ PR summary present 💯 
✔️ Linters are passing 💯 



## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-12 12:54 UTC, DuaneDave commented on index.html
> +    </nav>
1. Good job using the `nav` tag as a wrapper for the navbar in addition, I suggest wrapping the `nav` tag itself with a `header tag also to make your code more semantic.

  Also, I suggest using an `a` tag for the site's logo instead of an `h4` for better accessibility 

I have also noticed that the specified font in the Figma template is not in use here. Kindly use the correct font family in order to make the project more visually appealing and consistent with the Figma template.




2. I also recommend that you add proper styling (color, spacing, and icon) to the navbar in order for it to look more like the Figma design. Doing so will make the UI more attractive and properly positioned.

Your design

![nav](https://user-images.githubusercontent.com/84930355/212067987-bf715e1a-e40e-4ad5-a9dd-776b25969af9.PNG)


Figma design

![mon nav](https://user-images.githubusercontent.com/84930355/212068154-0c665786-577e-41f3-88bc-2ba7ea9ad776.PNG)

2023-01-12 12:54 UTC, DuaneDave commented on index.html
> +    <div class="body">
I suggest wrapping the headline section in a `section` instead of a `div` tag to make the code more organized, semantic, and readable. ([read morer about `section` tag here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section))

2023-01-12 12:54 UTC, DuaneDave commented on index.html
> +    </div>
It is advisable to use all images that are for design purposes and has no specific meaning to the websites as a background image in order to not confuse users using a screen reader.

2023-01-12 12:54 UTC, DuaneDave commented on index.html
> +        <h2 class="sub">I'm Brian</h2>
The salutation texts are both together and as such, I suggest using only an `h1` tag for it in oder to keep your tags more organized e.g 
`
'<h1 class="title">Hey There <br/> I am Brian</h1>'
`

2023-01-12 12:54 UTC, DuaneDave commented on index.html
> +    </div>
currently, your website is missing the social media icons which are useful for clients to get in touch with you, kindly add them (use aa `ul` tag) to the website as shown in the Figma template to aid users contact you

Your Design

![bad](https://user-images.githubusercontent.com/84930355/212067184-3d9b1899-f021-4225-885e-511cbb10a84f.PNG)



Figma Design

![proper icon](https://user-images.githubusercontent.com/84930355/212066393-55767ac4-0d63-4627-b566-1d1864cfc94a.PNG)


As seen above, you'd easily realize the positioning of the illustration in the Figma template is quite different from yours. I strongly recommend that you align the illustration to match the Figma design to make the UI more visually appealing.

2023-01-16 15:45 UTC, christianbiring1 reviewed
Hi @yegonkimutai , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# Invalid Code Review Request :heavy_multiplication_x: 
![Invalid](https://user-images.githubusercontent.com/97100091/212717414-99b63932-183e-485b-9e1f-eb3b816fb203.gif)

You have submitted a project, that has no linters checks set up correctly, Kindly make sure your linters checks are well set are all passing (green)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-01-16 16:43 UTC, yegonkimutai commented
Hello @christianbiring1 how can I request for the linters check since I have already made the corrections that were suggested?

2023-01-17 06:50 UTC, Nyame-Wolf requested changes
# STATUS: REQUIRED CHANGES :recycle: 

Hi @yegonkimutai  :wave: 

Your project page is looking fantastic so far :star_struck: ! 

However, there is still some room for improvement, that can help you have better code and make your project professional :sunglasses: 

![](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

## Highlights :sparkles:

- Great work using the right GitHub Flow :100: 
- Linters are passing ☑️ 

Congrats on your work so far! :clap:  

## Required Changes ♻️

There are some issues that you still need to work on to go to the next project, but you are almost there! 
_For more information, check the comments under the review :arrow_down:_

## Optional suggestions :ballot_box_with_check: 

_Every comment with the **[OPTIONAL]** prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can improve the quality of your code :100:_

Happy coding and keep it up! :raised_hands: 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
  Please, remember to tag me **@Nyame-Wolf**  in your question so I can receive the notification.

  **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------

  _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

2023-01-17 06:50 UTC, Nyame-Wolf commented on index.html
> +        <h4 class="logo">Brian Yegon</h4>
I suggest you change this from a `<h4>` to a link tag `<a>`. This is for three reasons: convention, semantics, and user experience(UX). [Check this link](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page) for more info.

2023-01-17 06:50 UTC, Nyame-Wolf commented on index.html
> +    <div class="body">
As previously recommended, I suggest you use a `<section>` tag instead of `<div>` tag. It represents a generic standalone section of the document, so use it. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section) for more info.

2023-01-17 06:50 UTC, Nyame-Wolf commented on index.html
> +    </div>
- I suggest you change this from image to css background image(decorations are always background images, not `img` tags). If an image is not part of the content (aesthetic reasons) use CSS background-image. [Check this link](https://stackoverflow.com/questions/492809/when-to-use-img-vs-css-background-image) for more info.(decorations are always background images, not img tags).



- Currently your page looks like this using the minimum allowed width of 375px
<img width="447" alt="Screenshot 2023-01-17 at 09 37 52" src="https://user-images.githubusercontent.com/48546992/212828284-10164dca-360f-403c-8c47-cf6ebd57a408.png">
And the hamburger icon cant be seen at a width of 500, where you have set your media query
<img width="681" alt="Screenshot 2023-01-17 at 09 44 37" src="https://user-images.githubusercontent.com/48546992/212828578-780088b0-956d-4ef3-969f-37d67d375f69.png">

It should look more like the template, that is:
<img width="372" alt="Screenshot 2023-01-17 at 09 48 06" src="https://user-images.githubusercontent.com/48546992/212829151-a9d9c4ab-0e16-4631-93fc-c68a790c5aa0.png">

2023-01-17 10:08 UTC, OyePriscilla requested changes
Hi @yegonkimutai 😃, 

You've really done a great work, I must confess!

There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close-so-close-seth-meyers](https://user-images.githubusercontent.com/103386183/196425615-8927e377-c543-407b-8da4-5c09fecc261b.gif)

## Highlights
Github flow observed✔️
Linters Set up correctly ✔️ 

## Required Changes ♻️


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-17 10:08 UTC, OyePriscilla commented on index.html
> +            </ul>
- [ ] You've done a great job by adding the social media icons, but you've not align them as we have it in the figma design. Kindly do this little adjustments. 👍 This will show hiring managers that you have the capability to reproduce perfectly any given design. 😄 
- [ ]  Please don't forget to wrap the individual items with a link `a` tag, this will give access to users to get in touch with you. 

## Your Design
![png-transparent-nigerian-naira-currency-symbol-symbol-miscellaneous-angle-text](https://user-images.githubusercontent.com/103386183/212868006-8a685698-cf77-4316-84f4-85b545e53da6.png)

## Figma Design
![png-transparent-nigerian-naira-currency-symbol-symbol-miscellaneous-angle-text](https://user-images.githubusercontent.com/103386183/212868149-6ed86a18-7b89-4fcd-8cb5-0bd199da7112.png)

2023-01-17 10:08 UTC, OyePriscilla commented on index.html
> +            don’t hesitate to contact me. I'm always ready to help</p>
- [optional] Please kindly ensure to use the given font as we have it in figma. It's optional because previous reviewers did not mentioned it. ℹ️

2023-01-17 15:38 UTC, algerina approved these changes
Hi @yegonkimutai ,
Good job so far! 

May I highlight the following:

- The repo looks professional.:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- Your project looks awesome:heavy_check_mark:

## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:
Your project is complete!  It's time to merge it :shipit:

<img src="https://media2.giphy.com/media/artj92V8o75VPL7AeQ/giphy.gif"/>

 
 ## Optional suggestions
 
 - Please check the comment under the review.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread and tag me @algerina if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [Algerina](https://github.com/algerina), I will receive a notification and will respond._

[GitHub](https://github.com/algerina) | [LinkedIn](https://linkedin.com/in/amel-khiri) | [Twitter](https://twitter.com/AmelQahwadji)

_Reviewed by [Amel Khiri ](https://github.com/algerina)_

2023-01-17 15:49 UTC, merged