body-project
yegonkimutai/Create-a-Portfolio pull request #2
Opened 2023-01-19 14:06 UTC by yegonkimutai

A continuation of the Portfolio project. The task included adding the contents of the profile as well as the about page

2023-01-19 16:05 UTC, roshan-bajgain requested changes
Hi @yegonkimutai, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 16:05 UTC, roshan-bajgain commented on index.html
> +                <h3 class="footer">See Project</h3>
- [ ] Your card is overlapping with the About section please fix it and also make the design similar to the Figma design.
- [ ] Also implement for all cards.
### Your design
![his](https://user-images.githubusercontent.com/81727988/213491190-70da0e06-6651-454a-8fb7-b1d62ac8cbd4.jpg)


### Figma design

![fimga](https://user-images.githubusercontent.com/81727988/213491521-603feea8-2d23-4a95-bb52-c4f41e4d4042.jpg)

2023-01-19 16:05 UTC, roshan-bajgain commented on index.html
> +        </section>
- [ ] You must stick to the design as much as possible like color, font, size, and background. Your design is overlapping so I would suggest you please fix this issue and also make every design of the `About section` similar to the Figma design. See the design below for reference.
### Your design
![your](https://user-images.githubusercontent.com/81727988/213492332-710f1cda-de4d-4a49-9f62-5fde58468515.jpg)

### Figma design
![fimga](https://user-images.githubusercontent.com/81727988/213492357-3198e6d6-9447-460d-8142-b253e80b0030.jpg)

2023-01-20 09:36 UTC, wayungi requested changes
Hi @yegonkimutai , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![image](https://user-images.githubusercontent.com/99656687/213657436-46310b5b-bbe4-4e5f-bbd7-a8b5343dce68.png)

 ## Highlights
- [ ] Good PR title 👍🏾 
- [ ] GitHub flow 👏🏾 
- [ ] Descriptive commit message 😄 
- [ ] Professional README 💯 
- [ ] All linter checks passing ✔️ 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._


 ## Required Changes ♻️
- [ ]  I noticed that you made very few changes recommended by the previous reviewer. To go to the next project and build your technical skills, you need to implement all the requested changes that are not [OPTIONAL]. Please open the Figma template and your project in the browser. Fire up your editor and fix up the issues one by one. Reach out to me on slack if anything is not clear. I will be happy to help.
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-20 09:36 UTC, wayungi commented on style.css
> +    grid-template-areas:
- [ ] Please fix the excess white space under your **My recent work**. Refer to this [document](https://cssgridgarden.com/) to test out your CSS grid syntax before applying it to the project.
_**Kindly remove this space**_
![speace-1](https://user-images.githubusercontent.com/99656687/213660127-b890c557-471b-4efe-ba13-7d17ff5990c2.png)

2023-01-20 09:36 UTC, wayungi commented on index.html
> +                </p>
- [ ] As requested by the previous reviewer, Please fix your design to match the Figma template. Your content is currently overlapping.

_**figman**_
![des-1](https://user-images.githubusercontent.com/99656687/213661625-b3b1145e-9c5c-464a-848f-8636f9393238.png)


_**Your design**_
![des-2](https://user-images.githubusercontent.com/99656687/213661667-48c2e762-52ae-445f-a819-c512a68d1a9c.png)

2023-01-20 09:48 UTC, yegonkimutai commented on index.html
> +                </p>
Hello @wayungi , please explain to me why my project is overlapping in your screen since in my screen i cant see the overlapping

2023-01-21 07:01 UTC, RiyaBulia12 approved these changes
## STATUS: APPROVED 🏆🥇 

### Hi @yegonkimutai  👋🏽  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
#### Congratulations! 🎉 🎉 🥳 🥳 

<img src="https://user-images.githubusercontent.com/50941074/190630799-31045ee0-2625-4964-92fa-9e77f79f6fda.gif"/>

## Highlights
* No Linter errors ✔️
* GitHub flow used ✔️
* Fixed the Previous CR comments ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-21 07:01 UTC, RiyaBulia12 commented on index.html
> +                </p>
Good job on fixing the overlapping issue. 🥳 
<img width="378" alt="Screenshot 2023-01-21 at 12 30 18 PM" src="https://user-images.githubusercontent.com/24832846/213848013-00d84b2c-ce28-4dba-a4d2-66e0a07b75a9.png">

2023-01-21 08:28 UTC, merged